name: terraform-install

on:
  push:
    branches:
      - master

jobs:
  Local-installation-of-terraform:
    name: Terraform for Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Terraform
        run: |
          cd terraform
          chmod +x terraform-install.sh
          sh terraform-install.sh
        shell: bash
      - name: Install Tflint
        run: |
          cd terraform
          chmod +x tflint.sh
          sh tflint.sh
        shell: bash
      - name: Upload the versions.txt file
        uses: actions/upload-artifact@v1
        with:
          name: terraform-versions
          path: terraform-versions.txt
      - name: Check the installation
        run: |
          cd terraform
          echo $(terraform version) > terraform-versions.txt
          echo $(tflint --version) >> terraform-versions.txt
        shell: bash
  Download-the-artifact:
    name: Download the artifact
    runs-on: ubuntu-latest
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v1
        with:
          name: terraform-versions
      - name: Check the versions
        run: |
          echo "Terraform version: $(cat terraform-versions.txt)"
          echo "Tflint version: $(cat terraform-versions.txt | tail -n +2)"
        shell: bash